# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5deda1287a25be0510680db23e45df1c31a45555c7bddf7cf848cafd71560e1036559a3303ce8e785761864f59f84c79c61dccb9be3ad54a55bb66eb0bda3f8b

test:
  secret_key_base: b5c739d022660ed540f81f1d53644567b6f3a1b0d25a1a3f8f8abf8013d9ae077300aadc1e57ad73e84d154ca4b864b474a030f6064d493a67eae42817e13bd5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
